# {{{
# Generated by zgen.
# This file will be overwritten the next time you run zgen save!

ZSH=/Users/yutaro/.zgen/sorin-ionescu/prezto-master

# ### Prezto initialization
zstyle ':prezto:module:prompt' 'theme' 'cloud'

# ### General modules
source "/Users/yutaro/.zgen/sorin-ionescu/prezto-master/init.zsh"
source "/Users/yutaro/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"
source "/Users/yutaro/.zgen/zsh-users/zsh-history-substring-search-master/zsh-history-substring-search.zsh"
source "/Users/yutaro/.zgen/unixorn/autoupdate-zgen-master/autoupdate-zgen.plugin.zsh"
source "/Users/yutaro/.zgen/unixorn/jpb.zshplugin-master/jpb.plugin.zsh"
source "/Users/yutaro/.zgen/unixorn/tumult.plugin.zsh-master/tumult.plugin.zsh"
source "/Users/yutaro/.zgen/djui/alias-tips-master/alias-tips.plugin.zsh"
source "/Users/yutaro/.zgen/unixorn/git-extra-commands-master/git-extra-commands.plugin.zsh"
source "/Users/yutaro/.zgen/skx/sysadmin-util-master/sysadmin-util.plugin.zsh"
source "/Users/yutaro/.zgen/peterhurford/git-it-on.zsh-master/git-it-on.plugin.zsh"
source "/Users/yutaro/.zgen/StackExchange/blackbox-master/blackbox.plugin.zsh"
source "/Users/yutaro/.zgen/sharat87/pip-app-master/pip-app.sh"
source "/Users/yutaro/.zgen/chrissicool/zsh-256color-master/zsh-256color.plugin.zsh"
source "/Users/yutaro/.zgen/RobSis/zsh-completion-generator-master/zsh-completion-generator.plugin.zsh"
source "/Users/yutaro/.zgen/rimraf/k-master/k.plugin.zsh"

# ### Plugins & Completions
fpath=(/Users/yutaro/.zgen/sorin-ionescu/prezto-master /Users/yutaro/.zgen/zsh-users/zsh-syntax-highlighting-master /Users/yutaro/.zgen/zsh-users/zsh-history-substring-search-master /Users/yutaro/.zgen/unixorn/autoupdate-zgen-master /Users/yutaro/.zgen/unixorn/jpb.zshplugin-master /Users/yutaro/.zgen/unixorn/tumult.plugin.zsh-master /Users/yutaro/.zgen/djui/alias-tips-master /Users/yutaro/.zgen/unixorn/git-extra-commands-master /Users/yutaro/.zgen/skx/sysadmin-util-master /Users/yutaro/.zgen/peterhurford/git-it-on.zsh-master /Users/yutaro/.zgen/StackExchange/blackbox-master /Users/yutaro/.zgen/sharat87/pip-app-master /Users/yutaro/.zgen/chrissicool/zsh-256color-master /Users/yutaro/.zgen/zsh-users/zsh-completions-master/src /Users/yutaro/.zgen/RobSis/zsh-completion-generator-master /Users/yutaro/.zgen/rimraf/k-master ${fpath})

autoload -Uz compinit && \
   compinit -C 

# ### Prezto modules
pmodload 'environment' 'terminal' 'editor' 'history' 'directory' 'spectrum' 'utility' 'completion' 'prompt' 'gnu-utility' 'git' 'osx' 'rsync' 'homebrew'
# }}}
